### PR TITLE
Fix gradient mixin

### LINKED ISSUE #459: Gradient mixin preventing transparency
Recently the gradient mixins changed to explicitly set `background-image` / `background-color` instead of relying on the shorthand `background`. This is preventing any gradients that make use of transparency from appearing transparent.

Screen Shot 2020-03-18 at 3 20 16 PM

### PR DESCRIPTION
**Pull request by alexpaxton**
Closes #459

### Changes

- Revert gradient mixins to set only the `background` property in shorthand
- Update contrast tester widget

### Screenshots

Screen Shot 2020-03-19 at 4 46 38 PM

### Checklist
Check all that apply

- [ ] Updated documentation to reflect changes
- [x] Added entry to top of Changelog with link to PR (not issue)
- [x] Tests pass
- [ ] Peer reviewed and approved
- [ ] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

File: src/Utils/colors.ts [hunk 1]
```diff
@@ -32,3 +33,24 @@ export const generateInlineCSSGradient = (
...
 }
+
+export const getAverageColorFromLinearGradient = (
+  linearGradient: string
+): string => {
+  const rgbColors = linearGradient.match(
+    /[rR][gG][bB][(]\d+[,]\s\d+[,]\s\d+[)]/g
+  )
+
+  // This function could fail if a linear gradient string is passed in using hexcodes
```
Comment (mavarius) [inline src/Utils/colors.ts]: We can do matching on the hex as well.
