### PR TITLE
Fix Validated Components

### LINKED ISSUE #339: Color picker always invalid
**Describe the bug**
ColorPicker is always passing back its new status as `Error` even when a valid hexcode is in there

This is causing some e2e tests to fail in InfluxDB

### PR DESCRIPTION
**Pull request by alexpaxton**
Closes #339 

Turns out the bug was caused by the hexcode validator function always returning a string when it was expecting a `null` value to determine if is valid, hence it always returning invalid

### Changes

- Change typing of `FormValidationElement` to expect `string` instead of `any`
  - Turns out the component is exclusively used to validate text inputs
- Remove state from `ColorPicker` and `FormValidationElement`
  - Should make these work like controlled components
- Create a type for `ValidationFunction` to enforce consistency across these components (and potentially more)
  - Validation functions should return a string (error) or null (valid)
- Add `validationFunc` prop to `ColorPicker`
  - Has a hexcode validator by default
  - User can pass in their own function
- Updated stories to include inputs for testing purposes

### Checklist
Check all that apply

- [x] Updated documentation to reflect changes
- [x] Added entry to top of Changelog with link to PR (not issue)
- [x] Tests pass
- [ ] Peer reviewed and approved
- [ ] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

File: src/Components/Button/Composed/ConfirmationButton.tsx [hunk 1]
```diff
@@ -110,9 +111,9 @@ const ConfirmationContents: FunctionComponent<{
   returnValue?: any
   onConfirm: (returnValue?: any) => void
   confirmationLabel: string
-  testID?: string
+  testID: string
```
Comment (drdelambre) [inline src/Components/Button/Composed/ConfirmationButton.tsx]: 😲

File: src/Components/ColorPicker/ColorPicker.tsx [hunk 2]
```diff
@@ -60,35 +57,26 @@ export const ColorPicker = forwardRef<ColorPickerSwatchRef, ColorPickerProps>(
       colors = influxColors,
       testID = 'color-picker',
       maintainInputFocus = false,
+      validationFunc = validateHexCode,
     },
     ref
   ) => {
-    const [errorMessage, setErrorMessage] = useState('')
+    const errorMessage = validationFunc(color)
```
Comment (drdelambre) [inline src/Components/ColorPicker/ColorPicker.tsx]: shouldn't this be more of a `validateHexCode(color) && validationFunc(color)` relationship? so that validating that a color matches a palette map somewhere doesnt mean you have to rewrite validateHexCode?

File: src/Components/ColorPicker/ColorPicker.tsx [hunk 3]
```diff
@@ -60,35 +57,26 @@ export const ColorPicker = forwardRef<ColorPickerSwatchRef, ColorPickerProps>(
...
-      const cleanedValue = trimmedValue
-        .split('')
-        .filter(char => HEX_CHARACTERS.includes(char.toLowerCase()))
-        .join('')
-
-      const newErrorMessage = validateHexCode(cleanedValue)
-
-      setErrorMessage(newErrorMessage)
-      onChange(cleanedValue, inputStatus)
+      onChange(e.target.value, inputStatus)
```
Comment (drdelambre) [inline src/Components/ColorPicker/ColorPicker.tsx]: why no more input cleaning here?

File: src/Components/ColorPicker/ColorPicker.tsx (hunk 2 above)
Comment (alexpaxton) [reply src/Components/ColorPicker/ColorPicker.tsx]: I made `validationFunc` to be `validateHexCode` by default, but in case we ever want to support rgb values or named colors a different validation function can be passed in

File: src/Components/ColorPicker/ColorPicker.tsx (hunk 3 above)
Comment (alexpaxton) [reply src/Components/ColorPicker/ColorPicker.tsx]: I suppose I could trim out space characters at the very least

**Comment by alexpaxton** [comment]
@drdelambre can you clarify "Chaining of validation"?

**Comment by drdelambre** [comment]
like.. whats the difference between a text input, color hex input, and a "only shades of grey" input? is the thinking that the last input is going to be `custom validation function + hex validation function + text validation function`, or is it `custom validation function implements (hex validation function + text validation function)`? is the idea that v1.0 is a transition from the former to the later?

File: src/Components/ColorPicker/ColorPicker.tsx (hunk 2 above)
Comment (drdelambre) [reply src/Components/ColorPicker/ColorPicker.tsx]: 👍
