### PR TITLE
fix: popover visibility

### LINKED ISSUE #326: Popovers that are initially visible stuck in top left
**Describe the bug**
It appears that when a `Popover` is set to be visible initially it renders in the top left corner and is unaffected by scroll or resize events

**To Reproduce**
I tested `master` of Clockface within InfluxDB using a relative path in `package.json`
Visit the `New Threshold Check` or `New Deadman Check` overlay
Notice the popover is not attached to the "Save" button

**Expected behavior**
The `Popover` should be affixed to the save button in the top right, and reposition when the screen is resized or scrolled

**Screenshots**
Screen Shot 2019-10-11 at 11 05 31 AM

### PR DESCRIPTION
**Pull request by alexpaxton**
Closes #326 

### Changes

- Remove `<span />` wrapping chil in `Popover`
- Popover `ref` prop passes through to "contents" element within `PopoverDialog`
- Use `useRef` instead of `createRef`
- Add popover to storybook examples that is visible by default (for testing purposes)
- Extract `createPortal` and `destroyPortal` functions into `/utils`
- Fire `handleUpdateStyles` on `PopoverDialog` initial render

Tested all changes in `influxdata/influxdb`

### Checklist
Check all that apply

- [x] Updated documentation to reflect changes
- [x] Added entry to top of Changelog with link to PR (not issue)
- [x] Tests pass
- [x] Peer reviewed and approved
- [ ] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

File: src/Components/Popover/Base/Popover.tsx [hunk 1]
```diff
@@ -55,13 +59,13 @@ export interface PopoverProps extends StandardFunctionProps {
...
 
-export type PopoverRef = HTMLSpanElement
+export type PopoverRef = PopoverDialogRef
 
 interface CustomMouseEvent extends MouseEvent {
   relatedTarget: Element
 }
 
-let uniquePortalID: string = ''
+const popoverPortalName = 'popover'
```
Comment (mavarius) [inline src/Components/Popover/Base/Popover.tsx]: Is this to be consistent for all shared for all popovers globally?

File: src/Components/Popover/Base/Popover.tsx [hunk 2]
```diff
@@ -88,6 +92,28 @@ export const PopoverRoot = forwardRef<PopoverRef, PopoverProps>(
     ref
   ) => {
     const [expanded, setExpanded] = useState<boolean>(!!visible)
+    const [portalID, setPortalID] = useState<string>('')
+
+    useEffect((): (() => void) => {
+      const newPortalID = `cf-${popoverPortalName}-portal-${uuid.v4()}`
+      !portalID && setPortalID(newPortalID)
```
Comment (mavarius) [inline src/Components/Popover/Base/Popover.tsx]: Since this effect only happens once, is this check actually doing anything?

File: src/Components/Popover/Base/Popover.tsx (hunk 1 above)
Comment (alexpaxton) [reply src/Components/Popover/Base/Popover.tsx]: yarrrr

File: src/Components/Popover/Base/Popover.tsx (hunk 2 above)
Comment (alexpaxton) [reply src/Components/Popover/Base/Popover.tsx]: I suppose it might be excessive, I'll test it w/o the check and see what happens
