### PR TITLE
Fix input padding in color picker component

### LINKED ISSUE #322: Color preview in color input covers the first two characters of the color input
## Reported in the issue [#15311](https://github.com/influxdata/influxdb/issues/15311) in the influxdb repository.

**Steps to reproduce the behavior:**
Input a new string into the `ColorPicker` component input.

**Expected behavior**
The full value of the input should still be visible alongside the color preview.

**Current behavior**
The color preview hides the first 2 characters of the string input.

**Screenshots**
Screenshot from 2019-10-04 13-42-25

**Browser**
 - OS: Linux (Ubuntu)
 - Browser: Chrome
 - Version: 76.0.3809.132 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by ahmedaabouzied**
Closes #322, influxdata/influxdb#15311

### Changes

Just a very little css fix for the color preview that was hiding the first two characters of the entered text input.

### Screenshots

Screenshot from 2019-10-04 21-15-47

### Checklist
Check all that apply

- [ ] Updated documentation to reflect changes
- [ ] Added entry to top of Changelog with link to PR (not issue)
- [x] Tests pass
- [ ] Peer reviewed and approved
- [x] Signed [CLA](https://influxdata.com/community/cla/) (if not already signed)

### CODE REVIEW

File: src/Components/ColorPicker/ColorPicker.tsx [hunk 1]
```diff
@@ -132,6 +132,7 @@ export const ColorPicker = forwardRef<ColorPickerSwatchRef, ColorPickerProps>(
           <Input
             className="cf-color-picker--input"
             placeholder="#000000"
+            inputStyle={{paddingLeft: '29px'}}
```
Comment (mavarius) [inline src/Components/ColorPicker/ColorPicker.tsx]: It might be better to do this in the stylesheet instead of inline using the `.cf-color-picker--input` class name.

Comment (ahmedaabouzied) [reply src/Components/ColorPicker/ColorPicker.tsx]: @mavarius okay then I'm on it

**Comment by alexpaxton** [comment]
@ahmedaabouzied hey there, we are aiming to release a new version of Clockface today. Are you able to update this PR in time? We'd love to incorporate your work
